[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "numwhale"
version = "0.1"
dependencies = []

[tool.setuptools.packages.find]
include = ["pimentel_math_utils*"]  # Adjust to only include the package(s) you want